### ISSUE TITLE
Install without internet connection

### ISSUE THREAD

**Issue by MikeZyatkov** [mongodb-js/kerberos#98] opened 2019-02-22 03:40 UTC
Hello! 
I don't have connection to the internet at my server, but I have proxy to  registry.npmjs.com. 
When I try install kerberos package I get some problem when prebuild-install script start.
How I can install kerberos on server without internet connection?
```
Error stack trace:
> kerberos@1.1.2 install C:\Programs\Projects\reference-api\node_modules\kerbero
s
> prebuild-install || node-gyp rebuild

prebuild-install WARN install getaddrinfo ENOTFOUND github.com github.com:443

C:\Programs\Projects\reference-api\node_modules\kerberos>if not defined npm_conf
ig_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lif
ecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  els
e (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node
-gyp.js" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the pac
kage itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind
a proxy or have bad
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\install.js:197:21)
gyp ERR! stack     at Request.emit (events.js:189:13)
gyp ERR! stack     at Request.onRequestError (C:\Program Files\nodejs\node_modul
es\npm\node_modules\request\request.js:881:8)
gyp ERR! stack     at ClientRequest.emit (events.js:189:13)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:392:9)
gyp ERR! stack     at TLSSocket.emit (events.js:189:13)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:82:8)
gyp ERR! stack     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19
)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Programs\Projects\reference-api\node_modules\kerberos
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN reference-api@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kerberos@1.1.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kerberos@1.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by mbroadst** [comment] 2019-02-22 14:21
Hey @MikeZyatkov, `prebuild-install` has a solution for this you can check out [here](https://github.com/prebuild/prebuild-install#custom-binaries). I'm going to close this as a duplicate of #90, please let us know if you have any other issues!

**Closed by mbroadst** 2019-02-22 14:21 UTC
