### ISSUE TITLE
npm install kerberos errors for node 12.1.0

### ISSUE THREAD

**Issue by larryosborn** [mongodb-js/kerberos#99] opened 2019-05-20 16:36 UTC
Installation fails for node v12.1.0

```
> kerberos@1.1.2 install /private/tmp/sample-app/node_modules/kerberos
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.1.0 runtime=node arch=x64 libc= platform=darwin)
  CXX(target) Release/obj.target/kerberos/src/kerberos.o
In file included from ../src/kerberos.cc:1:
In file included from ../src/kerberos.h:5:
../src/kerberos_common.h:29:43: error: no matching member function for call to 'Has'
    return !options.IsEmpty() && options->Has(key) && options->Get(key)->IsString()
                                 ~~~~~~~~~^~~
/Users/larry/.node-gyp/12.1.0/include/node/v8.h:3449:37: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Has(Local<Context> context,
                                    ^
/Users/larry/.node-gyp/12.1.0/include/node/v8.h:3455:37: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Has(Local<Context> context, uint32_t index);
                                    ^
In file included from ../src/kerberos.cc:1:
In file included from ../src/kerberos.h:5:
../src/kerberos_common.h:29:64: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return !options.IsEmpty() && options->Has(key) && options->Get(key)->IsString()
                                                               ^
/Users/larry/.node-gyp/12.1.0/include/node/v8.h:3412:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/larry/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/kerberos.cc:1:
In file included from ../src/kerberos.h:5:
../src/kerberos_common.h:30:57: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
               ? std::string(*(Nan::Utf8String(options->Get(key))))
                                                        ^
/Users/larry/.node-gyp/12.1.0/include/node/v8.h:3412:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/larry/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/kerberos.cc:1:
In file included from ../src/kerberos.h:5:
../src/kerberos_common.h:39:43: error: no matching member function for call to 'Has'
    return !options.IsEmpty() && options->Has(key) && options->Get(key)->IsNumber()
                                 ~~~~~~~~~^~~
/Users/larry/.node-gyp/12.1.0/include/node/v8.h:3449:37: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Has(Local<Context> context,
                                    ^
/Users/larry/.node-gyp/12.1.0/include/node/v8.h:3455:37: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Has(Local<Context> context, uint32_t index);
                                    ^
In file included from ../src/kerberos.cc:1:
In file included from ../src/kerberos.h:5:
../src/kerberos_common.h:39:64: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return !options.IsEmpty() && options->Has(key) && options->Get(key)->IsNumber()
                                                               ^
/Users/larry/.node-gyp/12.1.0/include/node/v8.h:3412:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/larry/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/kerberos.cc:1:
In file included from ../src/kerberos.h:5:
../src/kerberos_common.h:40:27: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
               ? options->Get(key)->Uint32Value()
                          ^
/Users/larry/.node-gyp/12.1.0/include/node/v8.h:3412:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/larry/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/kerberos.cc:1:
In file included from ../src/kerberos.h:5:
../src/kerberos_common.h:40:49: error: too few arguments to function call, single argument 'context' was not specified
               ? options->Get(key)->Uint32Value()
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/larry/.node-gyp/12.1.0/include/node/v8.h:2567:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/larry/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
4 warnings and 3 errors generated.
make: *** [Release/obj.target/kerberos/src/kerberos.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/tmp/sample-app/node_modules/kerberos
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN sample-app@1.0.0 No description
npm WARN sample-app@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kerberos@1.1.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kerberos@1.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/larry/.npm/_logs/2019-05-20T16_28_48_447Z-debug.log
```

**Comment by daprahamian** [comment] 2019-05-22 21:44
Thank you for filing @larryosborn. I opened https://jira.mongodb.org/browse/NODE-1984 to track this going forward.

**Comment by rayfoss** [comment] 2019-08-20 13:22
Perhaps we should drop kerberos support.... and any and all use of node-gyp for that matter. 99% of my node pain comes from it.

**Comment by anthonydresser** [comment] 2019-09-16 20:54
I saw that the your internal (jira) ticket for this is set to resolved. 

Whats the status of this being resolved for releases? Will newer prebuilts of electron and node also be published?

**Comment by mbroadst** [comment] 2019-09-17 13:38
@anthonydresser I just uploaded all the linux builds. The kerberos module isn't set up to run on our CI quite yet so this wasn't happening automatically. Will publish OSX packages this afternoon, thanks for notifying us

**Comment by pluma** [comment] 2020-02-16 13:16
It's February and kerberos still doesn't seem to build on node 12.

Is this module officially abandoned or are there any plans to port it in the near future?

**Comment by mbroadst** [comment] 2020-02-16 16:40
@pluma can you please provide details about your failed build? I can confirm the module builds against node 12 on my local machine, and all of the prebuilds for ABI 72 have been uploaded. The module is most certainly not abandoned, but we use JIRA to track everything related to the driver so GitHub issues can occasionally be lost in the mix. I'm going to close this issue now, please reopen if you continue to have any issues.

**Closed by mbroadst** 2020-02-16 16:40 UTC

**Comment by pluma** [comment] 2020-02-16 16:57
Odd. Must have been a caching issue. I cleared out the lockfile and `node_modules` but it seems like I still got `1.1.2` (without pinning). Now I'm getting `1.1.3` and it builds. Sorry about the noise.

**Comment by mbroadst** [comment] 2020-02-16 19:55
@pluma glad to hear it's working for you. As a reminder, in the future the best way to get our attention for some issue is through JIRA.

**Comment by kadosh1000** [comment] 2020-04-07 15:26
This keeps on happening to me.
Node 13.1.0
kerberos 1.1.3

> kerberos@1.1.3 install /var/kaholo-builds/kaholo_build_2020-3-7-14-48/kaholo/server/node_modules/kerberos
> prebuild-install || node-gyp rebuild
prebuild-install WARN install No prebuilt binaries found (target=13.1.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/var/kaholo-builds/kaholo_build_2020-3-7-14-48/kaholo/server/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/src/kerberos.o
In file included from ../src/kerberos_common.h:7:0,
                 from ../src/kerberos.h:5,
                 from ../src/kerberos.cc:1:
../src/unix/kerberos_gss.h:18:31: fatal error: gssapi/gssapi.h: No such file or directory
compilation terminated.
kerberos.target.mk:112: recipe for target 'Release/obj.target/kerberos/src/kerberos.o' failed
make: *** [Release/obj.target/kerberos/src/kerberos.o] Error 1
make: Leaving directory '/var/kaholo-builds/kaholo_build_2020-3-7-14-48/kaholo/server/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v13.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.4.0-1101-aws
gyp ERR! command "/root/.nvm/versions/node/v13.1.0/bin/node" "/root/.nvm/versions/node/v13.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/kaholo-builds/kaholo_build_2020-3-7-14-48/kaholo/server/node_modules/kerberos
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN kaholo-server@1.4.2 No description
npm WARN kaholo-server@1.4.2 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kerberos@1.1.3 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kerberos@1.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-07T15_20_44_820Z-debug.log

**Comment by mbroadst** [comment] 2020-04-07 17:45
@kadosh1000 the issue is that you don't have development headers for kerberos installed. See this line:
```
../src/unix/kerberos_gss.h:18:31: fatal error: gssapi/gssapi.h: No such file or directory
```
